import type { Metadata } from "next";
import "./styles/globals.css";
import { minhaFonte} from "@/app/font/font"
import Cabecalho from "@/components/Cabecalho/Cabecalho";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${minhaFonte.className} antialiased`}>
        <Cabecalho/>
        {children}
      </body>
    </html>
  );
}
