import { minhaFonte } from "@/app/font/font";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";
import "./styles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${minhaFonte.className} antialiased overflow-x-hidden`}>
        <Cabecalho />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
